# Generated by Django 4.2.7 on 2025-04-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examigo', '0002_semesterplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='semesterplan',
            name='content',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
