# Generated by Django 5.2 on 2025-04-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examigo', '0003_semesterplan_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time_limit',
            field=models.IntegerField(default=0),
        ),
    ]
