# Generated by Django 5.1.6 on 2025-05-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examigo', '0004_quiz_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='total_possible',
            field=models.FloatField(default=0),
        ),
    ]
