name: Build and Notify

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate a build process
        run: echo "Running build on branch ${{ github.ref_name }}..."

  notify:
    needs: build
    runs-on: ubuntu-latest
    if: always()  # always run this job after build
    steps:
      - name: Send Email via EmailJS
        run: |
          curl -X POST https://api.emailjs.com/api/v1.0/email/send \
            -H "Content-Type: application/json" \
            -d '{
              "service_id": "${{ secrets.EMAILJS_SERVICE_ID }}",
              "template_id": "${{ secrets.EMAILJS_TEMPLATE_ID }}",
              "user_id": "${{ secrets.EMAILJS_PUBLIC_KEY }}",
              "template_params": {
                "status": "${{ needs.build.result || 'success' }}",
                "branch": "${{ github.ref_name }}",
                "commit": "${{ github.event.head_commit.message }}",
                "author": "${{ github.actor }}"
              }
            }'
